$p = 'K:\yt_extension\yt_transcriber\src\ui\views\AiView.tsx'
$t = [IO.File]::ReadAllText($p)
$t = $t.Replace("'ai.status.saved'", "'general.success'")
$t = $t.Replace("'ai.error.permission'", "'ai.error.cors'")
$t = $t.Replace("s.tr('ai.status.test.ok')", "s.tr('ai.test.success')")
$t = $t.Replace("s.tr('ai.status.test.fail', { error: r.errorMessage ?? '' })", "s.tr('ai.test.failed')")
$t = $t.Replace("'ai.error.nokey'", "'ai.error.auth'")
$t = $t.Replace("'ai.error.strict'", "'ai.error.blockedStrict'")
$t = $t.Replace("s.tr('ai.error.generic', { error: r.errorMessage ?? r.errorCode ?? '' })", "``${s.tr('ai.error.network')} ${r.errorMessage ?? r.errorCode ?? ''}``")
$t = $t.Replace("'ai.key.label'", "'ai.apiKey'")
$t = $t.Replace("'ai.key.help'", "'ai.apiKey.hint'")
$t = $t.Replace("'ai.key.session'", "'ai.sessionOnly'")
$t = $t.Replace("'ai.key.save'", "'general.save'")
$t = $t.Replace("'ai.key.delete'", "'general.delete'")
$t = $t.Replace("'ai.hint'", "'ai.setup.description'")
$t = $t.Replace("s.tr('ai.consent.body')", "s.tr('ai.consent', { provider: provider?.label ?? '' })")
$t = $t.Replace("'ai.consent.confirm'", "'general.confirm'")
$t = $t.Replace("'ai.needs.transcript'", "'availability.not-a-video-page'")
$t = $t.Replace("'ai.qa.ask'", "'ai.qa'")
$t = $t.Replace("'ai.running'", "'ai.generating'")
$t = $t.Replace("'ai.copy'", "'transcript.copy.text'")
[IO.File]::WriteAllText($p, $t)
Write-Output "patched"
